"""Deep-learning explainer visual components for MotionGram scenes."""

from __future__ import annotations

from motiongram.deeplearning.algos import (
    CrossVal,
    DataSet,
    Intuition,
    LossFunction,
    Model,
    OptimizationAlgorithm,
    PracticalImplementation,
    ScratchImplementation,
    Summary,
    Theory,
    TrainTestSplit,
    Training,
    TrainingLoop,
    WhatIsMissing,
)
from motiongram.deeplearning.animators import AnimateAttribute, AnimateIntAttribute
from motiongram.deeplearning.autodiff import ComputationTape, DualNumberNode, TapeVisualizer
from motiongram.deeplearning.calculus import (
    ChainRule,
    Derivatives,
    Differentiation,
    Gradients,
    PartialDerivatives,
)
from motiongram.deeplearning.cnns import (
    Channels,
    ConvolutionalLayers,
    Convolutions,
    FeatureMap,
    ModernCNN,
    Padding,
    Pooling,
    ReceptiveField,
    Stride,
)
from motiongram.deeplearning.data_manipulation import (
    Broadcasting,
    Indexing,
    Operations,
    Slicing,
    Vectorization,
)
from motiongram.deeplearning.generalization import (
    Error,
    GeneralizationError,
    ModelSelection,
    Overfitting,
    TrainingError,
    Underfitting,
)
from motiongram.deeplearning.linear_algebra import (
    DotProducts,
    Matrices,
    MatrixMultiplication,
    Scalars,
    Tensors,
    VectorProducts,
    Vectors,
)
from motiongram.deeplearning.metrics import Metrics, Prediction
from motiongram.deeplearning.mlp import (
    ActivationFunctions,
    BackwardProp,
    ComputationalGraphs,
    Dropout,
    EarlyStopping,
    ExplodingGradients,
    ForwardProp,
    HiddenLayers,
    ParamInit,
    Regularization,
    VanishingGradients,
)

__all__ = [
    "AnimateAttribute",
    "AnimateIntAttribute",
    "ActivationFunctions",
    "BackwardProp",
    "Broadcasting",
    "ChainRule",
    "Channels",
    "ComputationTape",
    "ComputationalGraphs",
    "Convolutions",
    "ConvolutionalLayers",
    "CrossVal",
    "DataSet",
    "Derivatives",
    "Differentiation",
    "DotProducts",
    "Dropout",
    "DualNumberNode",
    "EarlyStopping",
    "Error",
    "ExplodingGradients",
    "FeatureMap",
    "ForwardProp",
    "GeneralizationError",
    "Gradients",
    "HiddenLayers",
    "Indexing",
    "Intuition",
    "LossFunction",
    "Matrices",
    "MatrixMultiplication",
    "Metrics",
    "Model",
    "ModelSelection",
    "ModernCNN",
    "Operations",
    "OptimizationAlgorithm",
    "Overfitting",
    "Padding",
    "ParamInit",
    "PartialDerivatives",
    "Pooling",
    "PracticalImplementation",
    "Prediction",
    "ReceptiveField",
    "Regularization",
    "Scalars",
    "ScratchImplementation",
    "Slicing",
    "Stride",
    "Summary",
    "TapeVisualizer",
    "Tensors",
    "Theory",
    "TrainTestSplit",
    "Training",
    "TrainingError",
    "TrainingLoop",
    "Underfitting",
    "VanishingGradients",
    "VectorProducts",
    "Vectorization",
    "Vectors",
    "WhatIsMissing",
]
