"""Typmotion — lightweight educational animation engine (pre-alpha stubs)."""

from __future__ import annotations

__version__ = "0.1.0a0"

from typmotion.animate import (
    Animator,
    Anticipate,
    Blur,
    CameraPan,
    CameraZoom,
    CircleOutline,
    Delay,
    ExaggerateEase,
    FadeIn,
    FadeOut,
    FollowThrough,
    MoveAlongPath,
    MoveArc,
    MoveX,
    MoveY,
    Parallel,
    Rotate,
    ScaleX,
    ScaleY,
    Sequence,
    SquashStretch,
    Stagger,
    TimeScale,
    WithSecondary,
    apply_timeline,
    lerp,
    smoothstep,
)
from typmotion.audio import KittenVoiceOverBackend, VoiceOver
from typmotion.canvas import Canvas, NullCanvas, RecordingCanvas
from typmotion.composition import (
    PHI,
    TAU,
    GesturePath,
    GoldenSpiral,
    RuleOfThirdsGrid,
    align,
    distribute_evenly,
    stack_vertical,
)
from typmotion.core import Camera, Circle, Node, Scene, Timeline
from typmotion.easing import (
    cubic_bezier,
    ease_in_back,
    ease_in_out_cubic,
    ease_in_out_quad,
    ease_out_back,
    ease_out_bounce,
    ease_out_elastic,
    linear,
    overshoot,
)
from typmotion.engine import step_frame
from typmotion.export import PyAVEncoder
from typmotion.form import Cube, Cylinder, Sphere
from typmotion.perspective import PerspectiveGrid
from typmotion.render import SkiaCanvas, SkiaRenderer
from typmotion.renderer import Renderer, ascii_frame_sha256, ascii_frame_text
from typmotion.shapes import (
    Arc,
    BezierCurve,
    Ellipse,
    Line,
    Path,
    Polygon,
    Rectangle,
    RegularPolygon,
)
from typmotion.text import CodeBlock, MathExpr, Text
from typmotion.typst_cache import cached_typst_svg_path, typst_cache_key
from typmotion.value import GradientOverlay, Shadow

__all__ = [
    "Animator",
    "Anticipate",
    "Arc",
    "BezierCurve",
    "Blur",
    "Camera",
    "CameraPan",
    "CameraZoom",
    "Canvas",
    "Circle",
    "CircleOutline",
    "CodeBlock",
    "Cube",
    "Cylinder",
    "Delay",
    "Ellipse",
    "ExaggerateEase",
    "FadeIn",
    "FadeOut",
    "FollowThrough",
    "GesturePath",
    "GoldenSpiral",
    "GradientOverlay",
    "KittenVoiceOverBackend",
    "Line",
    "MathExpr",
    "MoveAlongPath",
    "MoveArc",
    "MoveX",
    "MoveY",
    "Node",
    "NullCanvas",
    "Parallel",
    "Path",
    "PerspectiveGrid",
    "PHI",
    "Polygon",
    "PyAVEncoder",
    "RecordingCanvas",
    "Rectangle",
    "RegularPolygon",
    "Renderer",
    "Rotate",
    "RuleOfThirdsGrid",
    "ScaleX",
    "ScaleY",
    "Scene",
    "Sequence",
    "Shadow",
    "SkiaCanvas",
    "SkiaRenderer",
    "Sphere",
    "SquashStretch",
    "Stagger",
    "TAU",
    "Text",
    "TimeScale",
    "Timeline",
    "WithSecondary",
    "VoiceOver",
    "__version__",
    "align",
    "apply_timeline",
    "ascii_frame_sha256",
    "ascii_frame_text",
    "cached_typst_svg_path",
    "cubic_bezier",
    "distribute_evenly",
    "ease_in_back",
    "ease_in_out_cubic",
    "ease_in_out_quad",
    "ease_out_back",
    "ease_out_bounce",
    "ease_out_elastic",
    "lerp",
    "linear",
    "overshoot",
    "smoothstep",
    "stack_vertical",
    "step_frame",
    "typst_cache_key",
]

